#!/bin/bash -eu

source "$(dirname $BASH_SOURCE)"/om-cmd

# Get CF deployment guid
om_cmd curl -p /api/v0/deployed/products > deployed_products.json
ERT_DEPLOYMENT_NAME=$(jq -r '.[] | select( .type | contains("cf")) | .guid' "deployed_products.json")

# Get UAA BBR Credentials
om_cmd curl -p /api/v0/deployed/director/credentials/bbr_ssh_credentials > bbr_keys.json
BBR_PRIVATE_KEY=$(jq -r '.credential.value.private_key_pem' bbr_keys.json)

export ERT_DEPLOYMENT_NAME
export BBR_PRIVATE_KEY
